### ISSUE TITLE
ReadMe

### ISSUE THREAD

**Issue by ElijahKlein** [ElijahKlein/ECE-461-Project#19]
Create base value for lines of code of given test cases (Average of). Compare the length of the ReadMe to the base value for a percentage.

**Comment by ElijahKlein** [comment]
Elijah is getting the base value calculated, will add a comment once I have it

**Comment by ElijahKlein** [comment]
May need to consider for what we do if the value is larger than the base value, it would yield a percentage over 1.

**Comment by Matthew-Nale** [comment]
Base values for README lines have been determined, but changes to this should be made if needed

**Comment by Matthew-Nale** [comment]
If changes are made, document this in the correct Metric File issue, as this is due to a computation performed in that file
