### ISSUE TITLE
Size

### ISSUE THREAD

**Issue by ElijahKlein** [ElijahKlein/ECE-461-Project#21]
Considers total of lines of code, may add number of files.

1 / Total Lines of Code * Sub metric factor

**Comment by Matthew-Nale** [comment]
Size has been calculated using the REST API, which obtained the actual size of the project. This does not use lines of code, but rather an integer value from the GitHub API that describes the local cloning size (given in bytes). this data will be computed in the Responsiveness file, in addition to the Pull Request data
