### ISSUE TITLE
Closed Issues

### ISSUE THREAD

**Issue by ElijahKlein** [ElijahKlein/ECE-461-Project#23]
Number of closed issues relative to total

If we have time

**Comment by Matthew-Nale** [comment]
Closed issues and total issues can be obtained from issues.py by calling getIssuesByType(URL, type), where URL is the GitHub URL and type is the type of issue to obtain (closed, open, all)

**Comment by Matthew-Nale** [comment]
As mentioned above, a function in the issues.py Submodule can be used to obtain the number of closed issues and total issues. However, closed and total issues are not being used in computations at this time, as discussed in the previous meeting
