### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by ElijahKlein** [ElijahKlein/ECE-461-Project#24]
Two factors 70% Open Issues / User, 30% Total issues / User

**Comment by Matthew-Nale** [comment]
Will have to perform the calculations for 70/30 in the rust files calling for it. Issues.py can be used to obtain the needed information, such as open and closed issues

**Comment by Matthew-Nale** [comment]
Files in the Submodules directory (issues.py) have been completed. Can obtain number of closed, open, and all issues per repository. Additional functions can be added as needed
