### ISSUE TITLE
Licensing 

### ISSUE THREAD

**Issue by ElijahKlein** [ElijahKlein/ECE-461-Project#25]
Confirms if the licensing in the ReadMe specifically is compatible with "GNU Lesser General Public License v2.1", we need to research compatibility between this and the other licensing options available through GitHub

**Comment by Matthew-Nale** [comment]
Basic code done for Liscensing.py, which involved calling readme.py. Changes should be made to search for multiple licenses other than "MIT License", which should be a relatively simple change.

**Comment by Matthew-Nale** [comment]
Licensing is checking for the two known compatible licenses, so this is completed
