### ISSUE TITLE
Ramp Up Metric File

### ISSUE THREAD

**Issue by ElijahKlein** [ElijahKlein/ECE-461-Project#27]
Generates a metric value (Percentage value) using the sub metrics below. 

ReadMe
Comments

**Comment by Matthew-Nale** [comment]
A basic readme.py function has been created, which has a function to quickly determine the number of non-blank lines in the README

**Comment by Matthew-Nale** [comment]
Start of basic structure has begun, with a layout as described in the associated pull request

**Comment by Matthew-Nale** [comment]
RampUp.rs has been mostly completed. As mentioned, the number of comments per file would be too computationally expensive, as well as having to factor in multiple programming languages. Therefore, the weighting is based on the README length, which has been completed. Values for the length cutoffs can be changed easily as well

**Comment by Matthew-Nale** [comment]
RampUp.rs has been completed, so it is free to be closed
