### ISSUE TITLE
Responsiveness Metric File

### ISSUE THREAD

**Issue by ElijahKlein** [ElijahKlein/ECE-461-Project#28]
Generates a metric value (Percentage value) using the sub metrics below. 

Pull Requests
Size
Active Contributors
Closed Issues

**Comment by Matthew-Nale** [comment]
The pull_requests.py file has been worked on. Currently, a function exists to obtain the time since the last pull date, and another function obtains all pull dates in a semi-ordered list

**Comment by Matthew-Nale** [comment]
Responsiveness metric file has been completed, values can change if needed
