### ISSUE TITLE
Correctness Metric File

### ISSUE THREAD

**Issue by ElijahKlein** [ElijahKlein/ECE-461-Project#29]
Generates a metric value (Percentage value) using the sub metrics below. 

Issues

**Comment by Matthew-Nale** [comment]
The issues.py file has been created and worked on. Converting data from a Python file to a Rust file should be explored, as the functions in issue.py obtain information about the number of open, closed, or all issues.

**Comment by Matthew-Nale** [comment]
Since the issues.py function is working, I am going to start working on the Correctness Metric file. Since I do not know how to get the Python and Rust interaction happening, I will be providing inputs manually, which are determined by the main.py outputs

**Comment by Matthew-Nale** [comment]
Progress has been made, but the exact computation for the [0,1] value has not been identified yet. Currently planning on involving potentially watchers, forks, and stars, as the GitHub API does not show total users or downloads

**Comment by ElijahKlein** [comment]
I think that we can use a similar system as net score, apply weights then normalize? 
We can still take into account closed issues by making it closed / total.

**Comment by Matthew-Nale** [comment]
Working with Eric, a basic form of the Correctness.rs file has been completed. Closed issues could be added, but small values would be changed again, which is no big deal to change

**Comment by Matthew-Nale** [comment]
Finishing touches has been added to Correctness.rs in order to provide a good estimate of correctness of the repository by using the number of open issues.
