### ISSUE TITLE
Licensing Metric File

### ISSUE THREAD

**Issue by ElijahKlein** [ElijahKlein/ECE-461-Project#30]
Generates a metric value (Percentage value) using the sub metrics below. 

Licensing

**Comment by Matthew-Nale** [comment]
Licensing.py is almost complete. A call is made to readme.py to obtain information on if the README contains information on licensing. This value is either 1 or 0, depending on if the compatible licensing is included. Changes should be made to determine all kinds of compatible licensing, and search all keywords in the README for them

**Comment by Matthew-Nale** [comment]
Metric file has been completed. Changed may be made for the readme.py submodule, but that can be documented under the correct issues
