### ISSUE TITLE
Main File

### ISSUE THREAD

**Issue by ElijahKlein** [ElijahKlein/ECE-461-Project#31]
Generates each of the metric values and assigns a weight to them, then calculates a score out of 1 by dividing by 15 to normalize. Ranking and according weight below. 

Format: Rank. Metric (Weight)

1. Bus Factor (5)
2. Responsiveness (4)
3. Correctness (3)
4. Ramp Up (2)
5. Licensing (1)

**Comment by Matthew-Nale** [comment]
The main.py file in the overall structure is only for testing of python submodules. The finished main could be done in rust to increase lines of code in Rust

**Comment by ElijahKlein** [comment]
I think that would make sense and be an easy transfer over
