### ISSUE TITLE
GraphQL API Checkoff

### ISSUE THREAD

**Issue by ElijahKlein** [ElijahKlein/ECE-461-Project#34]
Mark complete when GraphQL API has been used.

**Comment by Matthew-Nale** [comment]
Since I can not seem to find a library to easily communicate with the GraphQL API, we may have to user 'requests' in python. A link to an example of this can be seen here: https://gist.github.com/gbaman/b3137e18c739e0cf98539bf4ec4366ad

**Comment by Matthew-Nale** [comment]
After further research, there does exist a GraphQL library for Python, if we wish to make things easier. A link to this library can be found here: https://github.com/DillonB07/GitAPI

**Comment by ElijahKlein** [comment]
I think that makes sense, I believe that we could import that as a dependency as well? Unless I'm missing something and don't need to which is possible

**Comment by Matthew-Nale** [comment]
If we use the pyGitAPI package, then we would just need to import as a dependency as well yes. If we use requests then I believe we won't need to, but I could be wrong on that
